name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_requests:
    branches: [ "main" ]

jobs:
  build_backend:
    name: Build Backend
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3 

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '20'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file pom.xml -DskipTests
      working-directory: backend

  build_frontend:
    name: Build Frontend
    needs: [build_backend]
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3 

    - name: Setup NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: '20'
    
    - name: Install dependencies
      run: npm i
      working-directory: frontend

    - name: Build
      run: npm run build
      working-directory: frontend

  unit_test:
    name: Build Unit Test
    runs-on: ubuntu-latest
    needs: [build_backend]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3 

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '20'
        cache: maven

    - name: SQL SetUp
      run: |
        sudo /etc/init.d/mysql start
        mysql -e 'CREATE DATABASE tadoo;' -uroot -proot

    - name: Import SQL Schema
      run: mysql -uroot -proot tadoo < database/schema.sql

    - name: Unit test
      run: mvn test
      working-directory: backend 
